### PR TITLE
Adding the possibility to fix a required size

### PR DESCRIPTION
**Pull request by aliabbas90**
Hi, 

In my application, I had to ignore some photos with unsatisfied size, that’s why I create this pull request.

Firstly, I added two configurations: `public var requiredSize: CGSize?`.

So, in the `cellForItemAt` method for collection view, I used the `phAsset. pixelHeight` and `phAsset. pixelWidth` to check the size. 

If the size is not conformed to `requiredSize`, I set the property (a new property) `unsatisfiedSize` for `TLPhotoCollectionViewCell` to false.

When this property is set and in the `didSet` method, I check if the value is `true` or `false` and according to this value, I show or not an overlay with the current image size. 

On cell selection, if this property (`unsatisfiedSize`) is set to false, I show a message in an alert. The title of this alert and the message can be configured with these two new configurations: `unsatisifiedSizeTitle` and `unsatisifiedSizeMessage`

### CODE REVIEW

**Comment by philippeauriach** [comment]
I think a more generic solution for the use case would be to create an optional method in the delegate, something like `shouldSelect(asset: TLPHAsset) -> Bool` , and then your implementation of the delegate could check the asset size and return false if it is too small. This would allow other type of check (like for example, if someone want to restraint users to pick too old pictures, to check the date time and display their own message)

**Comment by aliabbas90** [comment]
In this case, we should wait for the user to tap on the photo before tell him that the image can’t be selected. 
This is what this feature looks like:
 screen shot step 1 screen shot step 2

**Comment by aliabbas90** [comment]
Interesting!
Generic solution could be useful to handle multiple cases, indeed. Let me check that...

**Comment by philippeauriach** [comment]
Just a thing : I'm just giving my advice, I'm not a reviewer or maintainer of this lib, just a developer who use it :)

**Comment by aliabbas90** [comment]
What about this solution: 

In the `TLPhotosPickerViewControllerDelegate`, I added an optional function called `func overlayViewForAsset(asset: TLPHAsset) -> UIView?`. Then, in the `cellForItemAt` method, I can replace my old code with this: 
```
if let overLay = self.delegate?.overlayViewForAsset(asset: asset) {
    cell.addSubview(overLay)
}
```
> I will check later for a better solution to add the overlay on the cell. 

This is an example of the PhotoPickerWithNavigationViewController implementing this protocol: 

```
extension PhotoPickerWithNavigationViewController: TLPhotosPickerViewControllerDelegate {
    func overlayViewForAsset(asset: TLPHAsset) -> UIView? {
        guard let phAsset = asset.phAsset else {
            return nil
        }
        if phAsset.pixelHeight < 300 || phAsset.pixelWidth < 300 {
            let view = UIView(frame: CGRect(x: 0, y: 0, width: 200, height: 200))
            view.backgroundColor = UIColor.red
            return view
        }
        return nil
    }
}
```

**Comment by tilltue** [comment]
@aliabbas90 @philippeauriach 
I think there is a simple solution.
Please check this.
https://github.com/tilltue/TLPhotoPicker/commit/29b76dbb5c0cfafb46b2530fb298290bdff13034

**Comment by philippeauriach** [comment]
Does that mean that the image loaded in the collection view is the full size image ? I think the advantage of working with phassets is that you can require and display a small image, and then use the full size after selecting the one you want, so that image.size in your example will be the size of the UIImage displayed, and not the true pixel height of PHAsset ?

Aside of this, there is a typo in your solution : requiedSizeLabel => requiredSizeLabel

**Comment by tilltue** [comment]
How about filtering photo library by picture size?
I think If it can not be selected, it's better not to show it.
```swift
let options = configure.fetchOption ?? PHFetchOptions()
        options.sortDescriptors = [NSSortDescriptor(key: "creationDate", ascending: false)]
        let requiredSizePredicate = NSPredicate(format: "pixelHeight > %d AND pixelWidth > %d", 300,300)
        options.merge(predicate: requiredSizePredicate)
```

**Comment by philippeauriach** [comment]
That's clearly the best way IMO (unless the developer want to explain to the user why he cannot select this picture)

**Comment by tilltue** [comment]
@aliabbas90 @philippeauriach
Added update(with phAsset) method.
Don't you want to use custom cell?
https://github.com/tilltue/TLPhotoPicker/commit/fc0d2973c586b17f57a0dd86e7e986b5cde3f0bb

**Comment by philippeauriach** [comment]
This and the custom cell is perfect IMO

**Comment by aliabbas90** [comment]
Filtering photo library by picture size could be a little bit confused for user. Most of time he didn't know the size of its pictures, so he may not understand why the picture is not shown no ? He will maybe think that's a bug in the app..

**Comment by tilltue** [comment]
@aliabbas90 
Indeed. please check this.
I wish this is what you want.
https://github.com/tilltue/TLPhotoPicker/commit/3de48ac56e634c3fa60695a4c24457af6090863d

simulator screen shot - iphone x - 2018-06-16 at 00 20 14

Here the sample.
git branch : https://github.com/tilltue/TLPhotoPicker/tree/requied-image-size

**Comment by aliabbas90** [comment]
Thank you. 
So, let me summary. To handle the required size we should:

1. Create a custom cell with a new method called `update(with phAsset: PHAsset)`
2. Handle the selection with a closure property :   `shouldSelectedCell` (maybe call it `handleSelection`?)
or the delegate method: `func shouldSelectedCell(phAsset: PHAsset) -> Bool` maybe call it `canSelectedCell` ?)

Then in our view controller, add the closure to the `shouldSelectedCell` or implement the method `shouldSelectedCell`.

Thank you for the sample. I see now the benefit of subclassing the cell.

**Comment by tilltue** [comment]
@aliabbas90 
Basically, Yes.

**Comment by aliabbas90** [comment]
@tilltue Thank you. I prepare the new PR.

**Comment by tilltue** [comment]
Release 1.7.0

**Pull request closed without merging**
