### PR TITLE
carthage supprt

### PR DESCRIPTION
**Pull request by terenzeyuen**
fixed demo – navigation's image view should be aspect fit
fixed scale not using screen's scale at thumbnail
added carthage support

### CODE REVIEW

**Comment by terenzeyuen** [comment]
hey @tilltue, great library!

**Comment by tilltue** [comment]
@terenzeyuen 
I can't find example in workspace.

**Comment by terenzeyuen** [comment]
@tilltue oh, it should be in there like this.

screen shot 2017-12-12 at 11 58 04

**Comment by terenzeyuen** [comment]
@tilltue you really cant see the example project?

**Comment by tilltue** [comment]
No i can't see that.

**Comment by terenzeyuen** [comment]
Ah try Manage Schema and check the example project? @tilltue 
screen shot 2017-12-13 at 01 23 08
screen shot 2017-12-13 at 01 22 21

**Pull request closed without merging**
