### PR TITLE
Update to Swift5 and fix compiler warnings. Fix a threading issue resulting in crash.

### PR DESCRIPTION
**Pull request by mbarashkov**
Project updated to Swift 5. Compiler warnings fixed.
Also, makes image retrieval process more logical (updates requestIDs on the same thread) and fixes a crash if scrolling quickly over many iCloud-located images.

### CODE REVIEW

**Comment by tilltue** [comment]
Thank you for your help.
I did check the thread when read (or write) to 'requestIDs' dictionary.
But, even for now It is accessed to 'requestID' at each other thread. 
```
collectionView(_:cellForItemAt:)<NSThread: A> row : 1
collectionView(_:cellForItemAt:)<NSThread: A> row : 1
collectionView(_:cellForItemAt:)<NSThread: B> row : 2
collectionView(_:cellForItemAt:)<NSThread: B> row : 2
collectionView(_:cellForItemAt:)<NSThread: C> row : 3
...
collectionView(_:didEndDisplaying:forItemAt:)<NSThread: Main> row : 0
...
```
Use to SynchronizedDictionay Fixed this problem. 7f5d4e956539fa79e5a9bbb40c41d21d4202a392
It is unfortunately slower and incurs more memory due to the GCD overhead, but is that it’s accurate.
Please feel free to relay your comments, suggestions or corrections.

**Comment by wave2588** [comment]
Please solve this problem as soon as possible!
Thanks!!

**Comment by mbarashkov** [comment]
I'll close this pull request as you've already implemented what I did, but slightly differently.

**Comment by mboeddeker** [comment]
Is it possible, to get this into the Swift 4.2 Version ?

**Comment by mboeddeker** [comment]
Because fast scrolling on Version 1.8.3 crashes the app

**Comment by tilltue** [comment]
@mboeddeker 
Hi, Are you using the cocoapods?
And, Which TLPhotopicker library version do you use to?

**Comment by rizwan95** [comment]
@mboeddeker  Can you please give us some insight on where the crash is occurring? It will help us in debugging the issue.

**Comment by mboeddeker** [comment]
Hey, so we are using cocoapods right and our clients are working with Swift 4.2

So we implemented the Version 1.8.3 in our app, there we have that issue, that the app crashes, when we scroll to fast through the photolibrary.  In version 1.8.4 you fixed that, but this release is for swift 5.

**Comment by tilltue** [comment]
@mboeddeker 
I create a new branch
pod 'TLPhotoPicker', :git => 'https://github.com/tilltue/TLPhotoPicker.git', :branch => 'swift_4.2'

**Pull request closed without merging**
